/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.38.0
  Forc version: 0.35.5
  Fuel-Core version: 0.17.3
*/

import type {
  BN,
  BytesLike,
  Contract,
  DecodedValue,
  FunctionFragment,
  Interface,
  InvokeFunction,
} from 'fuels';

interface HeSaidContractAbiInterface extends Interface {
  functions: {
    did_say: FunctionFragment;
    say: FunctionFragment;
  };

  encodeFunctionData(functionFragment: 'did_say', values: [string]): Uint8Array;
  encodeFunctionData(functionFragment: 'say', values: [string]): Uint8Array;

  decodeFunctionData(functionFragment: 'did_say', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'say', data: BytesLike): DecodedValue;
}

export class HeSaidContractAbi extends Contract {
  interface: HeSaidContractAbiInterface;
  functions: {
    did_say: InvokeFunction<[said: string], boolean>;
    say: InvokeFunction<[said: string], void>;
  };
}
